import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="bg-[#080E1C] min-h-screen text-white">
      <nav className="sticky top-0 z-50 backdrop-blur-md border-b border-white/8" style={{ background: "rgba(8,14,28,0.85)" }}>
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center">
          <Link href="/" className="font-bold text-xl text-white">
            FIRE<span className="text-orange-500">path</span>
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-white mb-2">Terms of Use</h1>
        <p className="text-white/40 text-sm mb-10">Last updated: May 2026</p>

        <div className="space-y-8 text-white/70 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Not investment advice</h2>
            <p>
              FIREpath is a financial literacy and planning tool. It is <strong className="text-white">not</strong>{" "}
              registered with SEBI, RBI, or any other regulatory body. Nothing on this
              platform constitutes investment advice, financial advice, or a recommendation
              to buy or sell any security. All projections are estimates based on assumptions
              you provide and should not be relied upon for actual investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Eligibility</h2>
            <p>
              You must be at least 18 years old to use FIREpath. By creating an account,
              you confirm that you meet this requirement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Your account</h2>
            <p>
              You are responsible for maintaining the security of your account credentials.
              You must not share your account with others. We reserve the right to suspend
              or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Accuracy of projections</h2>
            <p>
              FIRE projections on FIREpath use assumed rates of return, inflation figures,
              and tax estimates that may not reflect your actual outcomes. Markets are
              unpredictable. Past performance assumptions are not indicative of future
              results. Use this tool as one input among many, not as a definitive plan.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">AI-generated content</h2>
            <p>
              Portfolio analyses are generated by the Google Gemini API and may contain
              errors or omissions. AI output is for informational purposes only. Always
              consult a qualified financial advisor before making significant financial
              decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Changes to these terms</h2>
            <p>
              We may update these terms from time to time. Continued use of FIREpath
              after changes constitutes acceptance of the revised terms. We will notify
              users of material changes via email.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Contact</h2>
            <p>
              Questions about these terms? Email{" "}
              <span className="text-orange-400">support@firepath.in</span>.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/8 text-xs text-white/30">
          © 2026 FIREpath. All rights reserved.
        </div>
      </div>
    </div>
  );
}
